package TransactionRules

import com.sample.TransactionDetails;
import java.util.Scanner;
import java.util.Arrays;
import java.util.ArrayList;
 
dialect "java"
salience 10

rule "Metropolitan City"
lock-on-active
    when
    	transaction : TransactionDetails(fScore != 100, Arrays.asList(MetroCities).contains(city.toLowerCase()))
    then
    	transaction.setMaxLimit(5000);
    	update(transaction)
    	System.out.println("Transaction Limit = 5000");
end

rule "Non-Metropolitan City"
lock-on-active
    when
    	transaction : TransactionDetails(fScore != 100 , !Arrays.asList(MetroCities).contains(city.toLowerCase()))
    then
        transaction.setMaxLimit(3000);
        update(transaction)
		System.out.println("Transaction Limit = 3000");
end